# Generated by Django 4.2.24 on 2025-09-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WikiConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language_code", models.CharField(max_length=10, unique=True)),
                ("auto_approve_groups", models.JSONField(default=list)),
            ],
            options={
                "ordering": ["language_code"],
            },
        ),
    ]
